name: "Pull request merged - Generate git tag with new version"

on:
  pull_request:
    types: 
      - closed
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  # Get latest tag currently in repo
  generate-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request && github.event.pull_request.merged == true }}
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      # Setup node for runner
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Get Latest Tag for Repo
      - name: "Get latest tag"
        id: "get-latest-tag"
        run: |
          # set -e

          # git config --global --add safe.directory /github/workspace

          git fetch --tags
          # This suppress an error occurred when the repository is a complete one.
          git fetch --prune --unshallow || true

          latest_tag=''

          # Get a latest tag in the shape of semver.
          # Define a readable semantic version regex pattern.
          # ^v?                  : Optional 'v' at the start
          # ([0-9]+)\.([0-9]+)\.([0-9]+) : Major.Minor.Patch numbers
          # (?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))? : Optional pre-release, e.g., -alpha.1
          # (?:\+[0-9A-Za-z-]+)? : Optional build metadata, e.g., +001
          # $                     : End of string
          SEMVER_REGEX='^v?\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\(-\([0-9A-Za-z-]\+\(\.[0-9A-Za-z-]\+\)*\)\)\?\(\+[0-9A-Za-z-]\+\)\?$'
          #git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/*"
          #git for-each-ref --sort=-creatordate --format '%(refname)' refs/tags
          for ref in $(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/*"); do
            tag="${ref}"
            echo "${tag}"
            if echo "${tag}" | grep -Eq "${SEMVER_REGEX}"; then
              latest_tag="${tag}"
              break
            fi
          done

          if [ "${latest_tag}" = '' ]; then
            latest_tag="v0.0.0"
          fi

          echo "tag=${latest_tag}" >> $GITHUB_OUTPUT


      # Set bump level based on pr labels
      - name: Set bump level
        id: set-bump-level
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./workflow-helpers/get-release-label.js');
            await script({github, context, core})

      # Bump Semver based on previous tag
      - run: npm install semver
      - name: "Bump semantic version"
        id: "bump-semver"
        env:
          INPUT_TAG: ${{ steps.get-latest-tag.outputs.tag }}
          BUMP_LEVEL: ${{ steps.set-bump-level.outputs.level }}
        uses: actions/github-script@v8
        with:
          script: |
            console.log(process.env.INPUT_TAG);
            const semver = require('semver');
            const script = require('./workflow-helpers/bump-semver.js');
            await script({ core }, semver)

      # Push new tag to repo
      - name: Push tag
        env:
          TAG: ${{ steps.bump-semver.outputs.new_version }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          MESSAGE="${TAG}: PR #${PR_NUMBER} ${PR_TITLE}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${TAG}" -m "${MESSAGE}"
          git push origin "${TAG}"


